import { useState, useCallback } from 'react';

const T = {
  bg: '#0a0a0a', surface: '#111111', elevated: '#1a1a1a',
  border: '#222222', borderLight: '#333333',
  red: '#8b0000', redLight: '#cc1a1a',
  purple: '#4b0082', purpleLight: '#9370db',
  text: '#e8e8e8', textMuted: '#888888', textDim: '#555555',
  white: '#ffffff', green: '#22c55e',
};
const FONT = `'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif`;
const MONO = `'JetBrains Mono', 'Fira Code', monospace`;

const DEFAULT_SECTIONS = [
  { id: 'about', title: 'About', content: '', placeholder: 'Brief description of what your site does and who it\'s for.' },
  { id: 'docs', title: 'Documentation', content: '', placeholder: 'Links to your main documentation, API docs, or guides.' },
  { id: 'api', title: 'API', content: '', placeholder: 'API endpoints, authentication methods, rate limits.' },
  { id: 'contact', title: 'Contact', content: '', placeholder: 'How AI agents or their operators should reach you.' },
];

const OPTIONAL_SECTIONS = [
  { id: 'pricing', title: 'Pricing', placeholder: 'Pricing tiers, free plans, enterprise options.' },
  { id: 'terms', title: 'Terms of Use', placeholder: 'Usage policies for AI agents accessing your content.' },
  { id: 'data', title: 'Data Handling', placeholder: 'How you handle data, privacy policy summary.' },
  { id: 'examples', title: 'Examples', placeholder: 'Example queries, use cases, or sample requests.' },
  { id: 'changelog', title: 'Changelog', placeholder: 'Recent updates, version history.' },
  { id: 'faq', title: 'FAQ', placeholder: 'Common questions AI agents might have.' },
];

export default function LLMSTxtGenerator() {
  const [siteName, setSiteName] = useState('');
  const [siteUrl, setSiteUrl] = useState('');
  const [siteDesc, setSiteDesc] = useState('');
  const [sections, setSections] = useState(DEFAULT_SECTIONS.map(s => ({ ...s })));
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [showInfo, setShowInfo] = useState(false);

  const updateSection = (id, field, val) => setSections(prev => prev.map(s => s.id === id ? { ...s, [field]: val } : s));
  const removeSection = (id) => setSections(prev => prev.filter(s => s.id !== id));
  const addSection = (tmpl) => { if (sections.find(s => s.id === tmpl.id)) return; setSections(prev => [...prev, { ...tmpl, content: '' }]); };
  const addCustom = () => setSections(prev => [...prev, { id: `custom_${Date.now()}`, title: 'New Section', content: '', placeholder: 'Add content.', custom: true }]);

  const available = OPTIONAL_SECTIONS.filter(o => !sections.find(s => s.id === o.id));

  const output = useCallback(() => {
    let o = `# ${siteName || 'Your Site Name'}\n\n`;
    if (siteUrl) o += `> ${siteUrl}\n\n`;
    if (siteDesc) o += `${siteDesc}\n\n`;
    for (const sec of sections) { if (sec.content.trim()) o += `## ${sec.title}\n\n${sec.content.trim()}\n\n`; }
    o += `---\nGenerated by OneKit LLMS.txt Generator\n`;
    return o;
  }, [siteName, siteUrl, siteDesc, sections])();

  const copyClip = () => { navigator.clipboard.writeText(output).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); }); };
  const downloadFile = () => { const b = new Blob([output], { type: 'text/plain' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = 'llms.txt'; a.click(); URL.revokeObjectURL(u); };

  const loadExample = () => {
    setSiteName('OneKit'); setSiteUrl('https://onekit.tools');
    setSiteDesc('OneKit is a free, privacy-first utility toolkit with 20+ browser-based tools. All processing happens client-side.');
    setSections([
      { id: 'about', title: 'About', content: 'OneKit provides free online tools including image stitching, video frame extraction, metadata stripping, PII redaction, and more. Every tool runs entirely in the browser.', placeholder: '' },
      { id: 'docs', title: 'Tools Available', content: '- ClipBreaker: Video to frame strip\n- Glyph Stitcher: Combine images\n- AI-Text Scrub: Redact sensitive data\n- Vibe-Check: Strip EXIF/GPS metadata\n- LLMS.txt Generator: AI-agent manifests\n- Plus 15+ utility tools', placeholder: '' },
      { id: 'api', title: 'Technical Details', content: 'Stack: Vite + React\nHosting: Vercel\nPrivacy: 100% client-side processing.', placeholder: '' },
      { id: 'contact', title: 'Contact', content: 'Email: admin@onekit.tools\nThis site is freely crawlable. Please respect rate limits.', placeholder: '' },
    ]);
  };

  const st = {
    input: { width: '100%', padding: '10px 14px', background: T.elevated, border: `1px solid ${T.border}`, borderRadius: 8, color: T.text, fontFamily: FONT, fontSize: 14, outline: 'none' },
    textarea: { width: '100%', minHeight: 80, padding: '10px 14px', background: T.elevated, border: `1px solid ${T.border}`, borderRadius: 8, color: T.text, fontFamily: MONO, fontSize: 12, lineHeight: 1.6, resize: 'vertical', outline: 'none' },
    label: { fontSize: 12, fontWeight: 600, color: T.textMuted, marginBottom: 6, display: 'block', textTransform: 'uppercase', letterSpacing: 0.5 },
    btn: (c = T.purple) => ({ padding: '10px 20px', background: c, color: T.white, border: 'none', borderRadius: 8, fontFamily: FONT, fontSize: 14, fontWeight: 600, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 8 }),
    btnSm: (c = T.purple) => ({ padding: '6px 14px', background: c, color: T.white, border: 'none', borderRadius: 6, fontFamily: FONT, fontSize: 12, fontWeight: 600, cursor: 'pointer' }),
    tab: (active) => ({ padding: '8px 16px', borderRadius: '8px 8px 0 0', fontSize: 12, fontWeight: 600, fontFamily: FONT, cursor: 'pointer', border: `1px solid ${T.border}`, borderBottom: 'none', background: active ? T.surface : 'transparent', color: active ? T.text : T.textDim }),
    card: { padding: 16, borderRadius: 10, marginBottom: 10, background: T.surface, border: `1px solid ${T.border}` },
    addBtn: { padding: '5px 12px', borderRadius: 6, fontSize: 10, fontWeight: 600, fontFamily: FONT, cursor: 'pointer', border: `1px solid ${T.border}`, background: 'transparent', color: T.textDim, display: 'inline-flex', alignItems: 'center', gap: 4 },
    customBtn: { padding: '5px 12px', borderRadius: 6, fontSize: 10, fontWeight: 700, fontFamily: FONT, cursor: 'pointer', border: `1px dashed ${T.purple}`, background: 'rgba(75,0,130,0.1)', color: T.purpleLight, display: 'inline-flex', alignItems: 'center', gap: 4 },
    preview: { width: '100%', minHeight: 200, padding: 16, borderRadius: 10, background: T.surface, border: `1px solid ${T.border}`, fontSize: 12, fontFamily: MONO, lineHeight: 1.7, whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: T.green, overflow: 'auto', maxHeight: 500 },
  };

  const filled = sections.filter(s => s.content.trim());

  return (
    <div>
      <div style={{ fontSize: 13, color: T.textMuted, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
        Generate AI-agent-readable manifests for your domain.
        <button onClick={() => setShowInfo(!showInfo)} style={{ background: 'none', border: 'none', color: T.purpleLight, cursor: 'pointer', fontSize: 11, fontWeight: 600, fontFamily: FONT }}>{showInfo ? 'Hide info' : 'What is llms.txt?'}</button>
        <button onClick={loadExample} style={{ fontSize: 11, color: T.purpleLight, background: 'none', border: 'none', cursor: 'pointer', fontFamily: FONT, textDecoration: 'underline', fontWeight: 600 }}>Load example</button>
      </div>

      {showInfo && (
        <div style={{ padding: 16, borderRadius: 10, marginBottom: 20, background: 'rgba(75,0,130,0.08)', border: '1px solid rgba(75,0,130,0.2)', fontSize: 12, color: T.textMuted, lineHeight: 1.6 }}>
          <strong style={{ color: T.purpleLight }}>llms.txt</strong> is an emerging standard (2026) that helps AI agents understand your website. Similar to how <code>robots.txt</code> tells crawlers what to index, <code>llms.txt</code> tells AI models what your site does and how to use it.
        </div>
      )}

      {/* Site info */}
      <div style={{ marginBottom: 16 }}><label style={st.label}>Site Name</label><input style={st.input} value={siteName} onChange={e => setSiteName(e.target.value)} placeholder="e.g. OneKit" /></div>
      <div style={{ marginBottom: 16 }}><label style={st.label}>Site URL</label><input style={st.input} value={siteUrl} onChange={e => setSiteUrl(e.target.value)} placeholder="e.g. https://onekit.tools" /></div>
      <div style={{ marginBottom: 16 }}><label style={st.label}>Description</label><input style={st.input} value={siteDesc} onChange={e => setSiteDesc(e.target.value)} placeholder="One-line description" /></div>

      <div style={{ height: 1, background: T.border, margin: '20px 0' }} />

      {/* Sections */}
      <label style={{ ...st.label, marginBottom: 12 }}>Sections</label>
      {sections.map(sec => (
        <div key={sec.id} style={st.card}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
            {sec.custom ? <input style={{ ...st.input, width: 200, padding: '6px 10px', fontSize: 13, fontWeight: 700 }} value={sec.title} onChange={e => updateSection(sec.id, 'title', e.target.value)} /> : <span style={{ fontSize: 13, fontWeight: 700, color: T.text }}>{sec.title}</span>}
            <button onClick={() => removeSection(sec.id)} style={{ background: 'none', border: `1px solid ${T.border}`, borderRadius: 5, width: 26, height: 26, cursor: 'pointer', color: T.textDim, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12 }}>×</button>
          </div>
          <textarea style={st.textarea} value={sec.content} onChange={e => updateSection(sec.id, 'content', e.target.value)} placeholder={sec.placeholder} />
        </div>
      ))}

      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', padding: '12px 0', borderTop: `1px solid ${T.border}`, marginTop: 8 }}>
        {available.map(o => <button key={o.id} style={st.addBtn} onClick={() => addSection(o)}>+ {o.title}</button>)}
        <button style={st.customBtn} onClick={addCustom}>+ Custom</button>
      </div>

      {/* Preview */}
      <div style={{ display: 'flex', gap: 4, marginTop: 20 }}>
        <button style={st.tab(!showPreview)} onClick={() => setShowPreview(false)}>Builder</button>
        <button style={st.tab(showPreview)} onClick={() => setShowPreview(true)}>Preview</button>
      </div>

      {showPreview && (
        <>
          <div style={st.preview}>{output}</div>
          <div style={{ display: 'flex', gap: 16, padding: '8px 0', fontSize: 11, color: T.textMuted }}>
            <span>Sections: <strong style={{ color: T.text }}>{filled.length}</strong></span>
            <span>Lines: <strong style={{ color: T.text }}>{output.split('\n').length}</strong></span>
            <span>Size: <strong style={{ color: T.text }}>{new Blob([output]).size} bytes</strong></span>
          </div>
          <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
            <button style={st.btn(T.purple)} onClick={copyClip}>{copied ? '✓ Copied!' : 'Copy to Clipboard'}</button>
            <button style={{ ...st.btnSm(T.elevated), border: `1px solid ${T.border}`, color: T.textMuted }} onClick={downloadFile}>⬇ Download llms.txt</button>
          </div>
        </>
      )}
    </div>
  );
}
